title: My Awesome Home
views:
  - title: Home
    path: home
    theme: dark-mode
    cards:
      - type: light
        entity: light.kontorslampa

      - type: light
        entity: light.bordslampa

  # 2nd tab to be used by robot vacuum
  - title: Robot
    path: robot
    cards:
      - type: 'custom:valetudo-map-card'
        entity: vaccuum.robot
        rotate: 0
        crop:
          top: 0
          bottom: 0
          left: 0
          right: 0
        min_height: 0
